--Query Optimization
--Analyzing query execution plans
--Using EXPLAIN or EXPLAIN ANALYZE
--Indexing Strategies
--Choosing the right indexes
--Managing index maintenance
--Partitioning
--Horizontal and vertical partitioning
--Benefits of partitioning